locals {
  name_prefix = "${var.project}-${var.environment}"
}

# Dedicated CMK (rather than the AWS-managed aws/s3 key) so key policy and
# rotation are under our control and auditable per environment.
resource "aws_kms_key" "meal_images" {
  description             = "${local.name_prefix} meal image bucket encryption key"
  deletion_window_in_days = 30
  enable_key_rotation     = true

  tags = merge(var.tags, {
    Name = "${local.name_prefix}-meal-images-key"
  })
}

resource "aws_kms_alias" "meal_images" {
  name          = "alias/${local.name_prefix}-meal-images"
  target_key_id = aws_kms_key.meal_images.key_id
}

resource "aws_s3_bucket" "meal_images" {
  bucket = var.bucket_name

  tags = merge(var.tags, {
    Name = "${local.name_prefix}-meal-images"
  })
}

# Meal photos are private-by-default and only ever served through
# pre-signed URLs generated by the backend - never made public.
resource "aws_s3_bucket_public_access_block" "meal_images" {
  bucket = aws_s3_bucket.meal_images.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_versioning" "meal_images" {
  bucket = aws_s3_bucket.meal_images.id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "meal_images" {
  bucket = aws_s3_bucket.meal_images.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm     = "aws:kms"
      kms_master_key_id = aws_kms_key.meal_images.arn
    }
    bucket_key_enabled = true
  }
}

# Meal photos lose analytical/user value quickly relative to their storage
# cost - transition to Infrequent Access and let expiration be opt-in per
# environment (disabled by default so nothing is deleted without a decision).
resource "aws_s3_bucket_lifecycle_configuration" "meal_images" {
  bucket = aws_s3_bucket.meal_images.id

  rule {
    id     = "meal-image-retention"
    status = "Enabled"

    filter {
      prefix = "meals/"
    }

    transition {
      days          = var.meal_image_retention_days
      storage_class = "STANDARD_IA"
    }

    dynamic "expiration" {
      for_each = var.meal_image_expiration_days > 0 ? [1] : []
      content {
        days = var.meal_image_expiration_days
      }
    }

    noncurrent_version_expiration {
      noncurrent_days = 30
    }
  }
}

resource "aws_s3_bucket_cors_configuration" "meal_images" {
  bucket = aws_s3_bucket.meal_images.id

  cors_rule {
    allowed_methods = ["GET", "PUT", "POST"]
    allowed_origins = ["*"]
    allowed_headers = ["*"]
    max_age_seconds = 3000
  }
}
